drop database if exists MyAreas;
create database MyAreas/*!40100 COLLATE 'utf8_general_ci' */;
use MyAreas;

create table std_users (user_id BigInt not null auto_increment  comment '用户序号',login_name varchar(255) not null  comment '登录名',active bool not null  comment '活跃',gender varchar(255) null  comment '性别',mobile varchar(255) null  comment '手机',mobile_public varchar(255) null  comment '公共手机',qq varchar(255) null  comment 'QQ ',weixin varchar(255) null  comment '微信',weibo varchar(255) null  comment '微博',nick_name varchar(255) null  comment '昵称',real_name varchar(255) null  comment '姓名',user_type Integer null  comment '类型',user_password varchar(255) null  comment '密码',start_date varchar(255) null  comment '开始日期',user_level Integer null  comment '等级',credit_level Integer null  comment '信用等级',user_comment Double null  comment '评价',birthday varchar(255) null  comment '生日',normal_address varchar(255) null  comment '地址',user_description text null  comment '描述',fee_level Integer null  comment '费率等级',token_id varchar(255) null  comment '令牌',latitude Double null  comment '纬度',longitude Double null  comment '经度',city_id BigInt null  comment '城市序号',primary key (user_id)) comment '用户';
create table std_stadiums (stadium_id BigInt not null auto_increment  comment '场馆序号',stadium_name varchar(255) not null  comment '场馆名称',active bool not null  comment '活跃',stadium_comment Double null  comment '评价',opentime varchar(255) null  comment '开放时间',latitude Double null  comment '纬度',longitude Double null  comment '经度',telephone varchar(255) null  comment '电话',detail varchar(255) null  comment '细节',can_park varchar(255) null  comment '能否停车',can_sell varchar(255) null  comment '是否有卖品部',can_rest varchar(255) null  comment '能否吃饭',can_rent varchar(255) null  comment '能否出租',can_card varchar(255) null  comment '是否可使用信用卡',can_bath varchar(255) null  comment '能否洗浴',can_long_buy varchar(255) null  comment '能否长定',ball_type Integer null  comment '球类类型',stadium_type Integer null  comment '场馆类型',city_id BigInt null  comment '城市序号',primary key (stadium_id)) comment '场馆';
create table std_stadium_pictures (stadium_picture_id BigInt not null auto_increment  comment '场馆图片序号',stadium_picture_name varchar(255) not null  comment '场馆图片名称',active bool not null  comment '活跃',stadium_id BigInt null  comment '场馆',picture varchar(255) null  comment '图片',primary key (stadium_picture_id)) comment '场馆图片';
create table std_stadium_areas (stadium_area_id BigInt not null auto_increment  comment '场馆区域序号',stadium_area_name varchar(255) not null  comment '场馆区域名称',active bool not null  comment '活跃',stadium_id BigInt null  comment '场馆',time_id BigInt null  comment '时间片序号',start_time varchar(255) null  comment '开始时间',end_time varchar(255) null  comment '结束时间',fee Double null  comment '费用',other_fee Double null  comment '其他费用',state Integer null  comment '状态',primary key (stadium_area_id)) comment '场馆区域';
create table std_stadium_comments (stadium_comment_id BigInt not null auto_increment  comment '场馆评论序号',stadium_comment_name text not null  comment '场馆评论名称',active bool not null  comment '活跃',stadium_id BigInt null  comment '场馆',user_id BigInt null  comment '用户',create_time varchar(255) null  comment '创建时间',star Integer null  comment '星标',comments text null  comment '评论',primary key (stadium_comment_id)) comment '场馆评论';


insert into std_users ( user_id,login_name,active,gender,mobile,mobile_public,qq,weixin,weibo,nick_name,real_name,user_type,user_password,start_date,user_level,credit_level,user_comment,birthday,normal_address,user_description,fee_level,token_id,latitude,longitude,city_id) values (1,'jerry',true,'Male','186211000000','186211000000','705880000','jerryshen','jerryshen','火鸟','沈戟峰',1,'1111','2017-12-01',5,5,5,'1972-11-02','利津路','jerry',5,'13498a1111',30,120,1);
insert into std_users ( user_id,login_name,active,gender,mobile,mobile_public,qq,weixin,weibo,nick_name,real_name,user_type,user_password,start_date,user_level,credit_level,user_comment,birthday,normal_address,user_description,fee_level,token_id,latitude,longitude,city_id) values (2,'mala',true,'Female','136419800000','136419800000','84400000','mala','mala','马拉','马拉',2,'2222','2017-12-01',1,1,1,'1980-07-01','武宁路','mala',1,'439898d2002',40,105,2);

insert into std_stadiums ( stadium_id,stadium_name,active,stadium_comment,opentime,latitude,longitude,telephone,detail,can_park,can_sell,can_rest,can_rent,can_card,can_bath,can_long_buy,ball_type,stadium_type,city_id) values (1,'源深体育中心',true,5,'09:00',30,120,'11111111','源深体育中心','true','true','true','true','true','true','true',1,1,1);
insert into std_stadiums ( stadium_id,stadium_name,active,stadium_comment,opentime,latitude,longitude,telephone,detail,can_park,can_sell,can_rest,can_rent,can_card,can_bath,can_long_buy,ball_type,stadium_type,city_id) values (2,'东方体育中心',true,4,'10:00',40,105,'22222222','东方体育中心','true','true','true','true','true','true','true',2,2,2);

insert into std_stadium_pictures ( stadium_picture_id,stadium_picture_name,active,stadium_id,picture) values (1,'源深体育中心',true,'1','');
insert into std_stadium_pictures ( stadium_picture_id,stadium_picture_name,active,stadium_id,picture) values (2,'东方体育中心',true,'2','');

insert into std_stadium_areas ( stadium_area_id,stadium_area_name,active,stadium_id,time_id,start_time,end_time,fee,other_fee,state) values (1,'源深体育中心片区1',true,'1',0,'10:00','12:00',100,20,1);
insert into std_stadium_areas ( stadium_area_id,stadium_area_name,active,stadium_id,time_id,start_time,end_time,fee,other_fee,state) values (2,'东方体育中心片区1',true,'2',0,'14:00','17:00',120,20,2);

insert into std_stadium_comments ( stadium_comment_id,stadium_comment_name,active,stadium_id,user_id,create_time,star,comments) values (1,'源深体育中心评论1',true,'1','1','10:00',4,'太好了');
insert into std_stadium_comments ( stadium_comment_id,stadium_comment_name,active,stadium_id,user_id,create_time,star,comments) values (2,'东方体育中心评论1',true,'2','2','14:00',5,'真是太好了');
